// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrfR4ExxowkcqnlNrdBpfE3XOeOZRUEYM',
    appId: '1:726437616352:android:e9f9900d95b275e5ef0e85',
    messagingSenderId: '726437616352',
    projectId: 'alora-ai-1135b',
    storageBucket: 'alora-ai-1135b.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjgnS9PWdhZLQuHpBfHrbi-gLnQl7cjhI',
    appId: '1:726437616352:web:418cdc4d7abbbc0bef0e85',
    messagingSenderId: '726437616352',
    projectId: 'alora-ai-1135b',
    authDomain: 'alora-ai-1135b.firebaseapp.com',
    storageBucket: 'alora-ai-1135b.firebasestorage.app',
    measurementId: 'G-8HVDRT60YY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8PwRfv_G17VEj0ZYDKJINTA0733AWdNM',
    appId: '1:726437616352:ios:169d000dc66286d6ef0e85',
    messagingSenderId: '726437616352',
    projectId: 'alora-ai-1135b',
    storageBucket: 'alora-ai-1135b.firebasestorage.app',
    iosClientId: '726437616352-p4gtr4h7e0qfc8vh4pce0tgtk1b80e0a.apps.googleusercontent.com',
    iosBundleId: 'com.aloraai.app.macos',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8PwRfv_G17VEj0ZYDKJINTA0733AWdNM',
    appId: '1:726437616352:ios:10c056275e12cb5def0e85',
    messagingSenderId: '726437616352',
    projectId: 'alora-ai-1135b',
    storageBucket: 'alora-ai-1135b.firebasestorage.app',
    iosClientId: '726437616352-j2g70uv0qs2i2ahquoubqomnsbou86me.apps.googleusercontent.com',
    iosBundleId: 'com.aloraai.app',
  );
}
